INSERT INTO SEMIMAGICSQUARE(ORIGINALSQUARE, NEWSEMIMAGICSQUARE, LOWESTCOST, SIZESIDE) VALUES ('Learn PHP','dsf','sdfsdf', 'John Poul');
INSERT INTO TWOARRAYS(FIRSTARRAY, SECONDARRAY, RESULT) VALUES ('Learn PHP','dsf','sdfsdf');

alter table TWOARRAYS alter column DATEOFRECORDING SET DEFAULT now;

create table SEMIMAGICSQUARE (
    ID INTEGER IDENTITY NOT NULL PRIMARY KEY,
    ORIGINALSQUARE VARCHAR(150) NOT NULL,
    NEWSEMIMAGICSQUARE VARCHAR(150) NOT NULL,
    LOWESTCOST int NOT NULL,
    SIZESIDE VARCHAR(50) NOT NULL,
    DATEOFRECORDING TIMESTAMP DEFAULT NOW
    );
create table TWOARRAYS (
    ID INTEGER IDENTITY NOT NULL PRIMARY KEY,
    FIRSTARRAY VARCHAR(250) NOT NULL,
    SECONDARRAY VARCHAR(250) NOT NULL,
    RESULT VARCHAR(250) NOT NULL,
    DATEOFRECORDING TIMESTAMP DEFAULT NOW
    );


